/*! \file
	Copyright Notice:

	Copyright (C) 1990-2015, International Business Machines
	Corporation and others. All rights reserved
*/
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_OPENTM2TOOLSLAUNCHER_DIALOG 102
#define IDR_MAINFRAME                   128
#define IDD_DLG_TOOLLAUNCHER            129
#define IDD_DLG_ADL                     132
#define IDD_DLG_EXP2TMX                 133
#define IDD_DLG_CHANGEFXP               134
#define IDD_DLG_CHKCALC                 135
#define IDD_DLG_CARETEITMFROMMEMORY     137
#define IDD_DLG_MTEVAL                  138
#define IDD_DLG_TMXSPLITSEGMENTS        139
#define IDD_DLG_REMOVETAGS              140
#define IDD_DLG_SHOWFXP                 141
#define IDD_DLG_TMX2EXP                 142
#define IDD_DLG_TMX2TEXT                143
#define IDD_DLG_XLIFF2EXP               144
#define IDD_DLG_MIGRATOR                145
#define IDD_DLG_GETTOOLINFO             146
#define IDD_DLG_GETREPORTDATA           147
#define IDD_DLG_MEMTOOL                 148
#define IDC_TAB_TOOLLAUNCHER            1000
#define IDC_LIST_TOTAL                  1003
#define IDC_LIST_SELECTED               1004
#define IDC_BUTTON_OPENTM2SCRIPTERGUI   1005
#define IDC_BUTTONOTMITM                1006
#define IDC_BUTTON_UNSELECT             1007
#define IDC_BUTTON_SELECT               1008
#define IDC_BUTTON_SELECALL             1009
#define IDC_CHECK_ADL_FOL               1011
#define IDC_ADL_CHECK_DIC               1012
#define IDC_BUTTON_REMOVEALL            1012
#define IDC_CHECK_ADL_MEM               1013
#define IDC_ADL_EDIT_FOL                1014
#define IDC_ADL_EDIT_MEM                1015
#define IDC_ADL_EDIT_DICT               1016
#define IDC_BUTTON_ADL_MEM              1017
#define IDC_BUTTON_ADL_FOL              1018
#define IDC_BUTTON_ADL_DICT             1019
#define IDC_EXP2TMX_CHECK_OUTMODE       1019
#define IDC_BUTTON_ADL_RUN              1020
#define IDC_REMOETAGS_CHECK_MARKUP      1020
#define IDC_TMX2EXP_CHECK_CLEANTF       1020
#define IDC_EXP2TMX_CHECK_NOCRLF        1020
#define IDC_BUTTON_ADL_HELP             1021
#define IDC_CHECK_CHK_ALL               1021
#define IDC_MEMTOOL_CHECK_FROMLANG      1021
#define IDC_LIST_ADL_LOG                1022
#define IDC_LIST_LOG                    1022
#define IDEXIT                          1023
#define IDC_TMX2EXP_CHECK_SS            1023
#define IDC_MEMTOOL_CHECK_TOLANG        1023
#define IDC_EXP2TMX_COMBO_OUTMODE       1024
#define IDC_MEMTOOL_CHECK_DATE          1024
#define IDC_EXP2TMXCOMBO_INMODE         1025
#define IDC_MEMTOOL_CHECK_DOC           1025
#define IDC_EXP2TMX_EDIT_INMEM          1026
#define IDC_EXP2TMX_EDIT_FOL            1027
#define IDC_EXP2TMX_EDIT_OUTMEM         1027
#define IDC_MEMTOOL_CHECK_CLEAR         1027
#define IDC_EXP2TMX_CHECK_OUTMEM        1028
#define IDC_CHANGEFXP_EDIT_PW           1028
#define IDC_MEMTOOL_CHECK_SET           1028
#define IDC_EXP2TMX_CHECK_INMODE        1029
#define IDC_CHANgeFXP_EDIT_SHIP         1029
#define IDC_MEMTOOL_CHECK_TYPE          1029
#define IDC_BUTTON_INMEM                1030
#define IDC_EDIT_TMXSPLITSEG_LOG        1030
#define IDC_BUTTON_OUTMEM               1031
#define IDC_EDIT_TMXSPLITSEG_OUTMEM     1031
#define IDC_EXP2TMX_LIST_LOG            1032
#define IDC_TMX2EXP_CHECK_INCLUDEBRACE  1032
#define IDC_EXP2TMX_BUTTON_RUN          1033
#define IDC_EXP2TMX_BUTTON_HELP         1034
#define IDC_TMX2EXP_EDIT_MARKUP         1034
#define IDC_CHANGEFXP_EDIT_FOLDERFILE   1035
#define IDC_MEMTOOL_EDIT_REV            1035
#define IDC_BUTTON_FOLDERFILE           1036
#define IDC_MEMTOOL_EDIT_TOMARKUP       1036
#define IDC_CHANGEFXP_CHECK_TYPE        1037
#define IDC_CITMFM_EDIT_OUT             1037
#define IDC_MEMTOOL_EDIT_FROMLANG       1037
#define IDC_CHANGEFXP_CHECK_PW          1038
#define IDC_MEMTOOL_EDIT_TOLANG         1038
#define IDC_CHANGEFXP_CHECK_SHIP        1039
#define IDC_MEMTOOL_EDIT_DATE           1039
#define IDC_CHANGEFXP_BUTTON_RUN        1040
#define IDC_MEMTOOL_EDIT_DOC            1040
#define IDC_CHANGEFXPCOMBO_TYPE         1041
#define IDC_MEMTOOL_EDIT_OUT            1041
#define IDC_CHECK_CHK_FLD               1042
#define IDC_TMXSPLITSEG_CHECK_LOG       1042
#define IDC_CHECK_CHK_FXP               1043
#define IDC_COMBO_TMXSPLITSEG_LOGS      1043
#define IDC_CHECK_CHK_HLOG              1044
#define IDC_TMXSPLITSEG_CHECK_LOGS      1044
#define IDC_CHK_EDIT_FLD                1045
#define IDC_TMXSPLITSEG_CHECK_OUTPUTMEM 1045
#define IDC_BUTTON_CHK_FLD              1046
#define IDC_CHK_EDIT_FXP                1047
#define IDC_CHK_EDIT_HLOG               1048
#define IDC_BUTTON_CHK_FXP              1049
#define IDC_BUTTON_CHK_HLOG             1050
#define IDC_BUTTON_CHKCALC_RUN          1051
#define IDC_SCROLLBAR1                  1052
#define IDC_CITMFM_EDIT_IN              1053
#define IDC_CITMFM_BUTTON_RUN           1055
#define IDC_MTEVAL_EDIT_FSP             1056
#define IDC_MTEVAL_EDIT_OUTFILE         1057
#define IDC_BUTTON_MTEVAL_FILESPEC      1058
#define IDC_BUTTON_MTEVAL_OUTFILE       1059
#define IDC_CHECK_MTEVAL_OUT            1060
#define IDC_CHECK_MTEVAL_DETAILS        1061
#define IDC_BUTTON_MTEVAL_RUN           1062
#define IDC_TMXSPLITSEG_EDIT_INMEM      1063
#define IDC_BUTTON_TMSPLITSEG_INMEM     1066
#define IDC_TMXSPLITSEG_BUTTON_RUN      1067
#define IDC_BUTTON_TMSPLITSEG_INMEM2    1068
#define IDC_BUTTON_TMSSPLITSEG_OUTMEM   1068
#define IDC_REMOVETAGS_EDIT_INMEM       1069
#define IDC_REMOVETAGS_EDIT_OUTMEM      1070
#define IDC_REMOVETAGSCOMBO_INMODE      1071
#define IDC_RMEOVETAGS_COMBO_OUTMODE    1072
#define IDC_REMOVETAGS_BUTTON_RUN       1074
#define IDC_SHOWFXP_EDIT_FSP            1075
#define IDC_CHECK_SHOWFXP_DETAILS       1076
#define IDC_BUTTON_SHOWFXP_FILESPEC     1077
#define IDC_BUTTON_SHOWFXP_RUN          1078
#define IDC_TMX2EXP_EDIT_INMEM          1079
#define IDC_TMX2EXP_EDIT_OUTMEM         1080
#define IDC_TMX2EXPCOMBO_OUTMODE        1081
#define IDC_TMX2EXP_BUTTON_INMEM        1082
#define IDC_tMX2EXP_CHECK_MARKUP        1083
#define IDC_TMX2EXP_CHECK_OUTMODE       1084
#define IDC_TMX2EXP_CHECK_OUTMEM        1085
#define IDC_MEMTOOL_CHECK_FROMMARKUP    1085
#define IDC_TMX2EXP_BUTTON_RUN          1086
#define IDC_MEMTOOLCOMBO_TASK           1087
#define IDC_CHECK_TMX2TEXT_OUTFILE      1088
#define IDC_TMX2TEXT_BUTTON_RUN         1089
#define IDC_TMX2TEXT_EDIT_OUT           1090
#define IDC_TMX2TEXT_EDIT_IN            1091
#define IDC_BUTTON_TMX2TEXT_INFILE      1092
#define IDC_BUTTON_TMX2TEXT_OUTFILE     1093
#define IDC_XLIFF2EXP_EDIT_IN           1094
#define IDC_XLIFF2EXP_EDIT_OUT          1095
#define IDC_CHECK_XLIFF2EXP_OUTFILE     1096
#define IDC_BUTTON_XLIFF2EXP_INFILE     1097
#define IDC_CHECK_GETTOOLINFO_CMD       1097
#define IDC_BUTTON_XLIFF2EXP_OUTFILE    1098
#define IDC_XLIFF2EXP_BUTTON_RUN        1099
#define IDC_CHECK_MIG_MEM               1100
#define IDC_MIG_BUTTON_RUN              1101
#define IDC_CHECK_GETTOOLINFO_UI        1102
#define IDC_GETTOOLINFO_BUTTON_RUN      1103
#define IDC_CHECK_MIG_FOLDER            1104
#define IDC_GETRPD_EDIT_IN              1104
#define IDC_CHECK_MIG_SETTING           1105
#define IDC_BUTTON_GETRPD_INFILE        1105
#define IDC_CHECK_MIG_ANA               1106
#define IDC_GETRPD_BUTTON_RUN           1106
#define IDC_CHECK_MIG_SHMEM             1107
#define IDC_MEMTOOL_EDIT_MEM            1107
#define IDC_CHECK_MIG_DICT              1108
#define IDC_MEMTOOL_EDIT_FROMMARKUP     1108
#define IDC_CHECK_MIG_CALCPROFILE       1109
#define IDC_CHECK_MIG_ALL               1110
#define IDC_MEMTOOL_CHECK_TOMAKRUP      1110
#define IDC_MEMTOOL_BUTTON_RUN          1111
#define IDC_COMBO1                      1112
#define IDC_RMEOVETAGS_COMBO_MARKUP     1112
#define IDC_MEMTOOL_COMBO_FROMMARKUP    1112
#define IDC_MEMTOOL_COMBO_FROMLANG      1116
#define IDC_MEMTOOL_COMBO_TOLANG        1117
#define IDC_MEMTOOL_COMBO_FROMMARKUP2   1118
#define IDC_MEMTOOL_COMBO_TOMARKUP      1118

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1113
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
