// Copyright (c) 2012-2016, International Business Machines
// Corporation and others.  All rights reserved.
//
#define STR_DRIVER_LEVEL           "Version 1.3.0"

#define STR_DRIVER_LEVEL_NUMBER    "1.3.0"
#define STR_COPYRIGHT  "Copyright (c) 2012-2016, International Business Machines Corporation and others.  All rights reserved."

// current version in numnerical format
// EQF_DRIVER_BUILD should be incremented for every build
#define EQF_DRIVER_VERSION    1
#define EQF_DRIVER_RELEASE    3
#define EQF_DRIVER_SUBRELEASE 0
#define EQF_DRIVER_BUILD      0

// text displayed in workbench titlebar
#define STR_TWBM_TITLE           "OpenTM2 Community Edition"

#define STR_TWBM_TITLE_LOGOS     "n/a"

