// Copyright (c) 2012-2019, International Business Machines
// Corporation and others.  All rights reserved.
//
#define STR_DRIVER_LEVEL           "Version 1.6.1"

#define STR_DRIVER_LEVEL_NUMBER    "1.6.1"
#define STR_COPYRIGHT  "Copyright (c) 2012-2019, International Business Machines Corporation and others.  All rights reserved."

// current version in numnerical format
// EQF_DRIVER_BUILD should be incremented for every build
#define EQF_DRIVER_VERSION    1
#define EQF_DRIVER_RELEASE    6
#define EQF_DRIVER_SUBRELEASE 1
#define EQF_DRIVER_BUILD      0

// text displayed in workbench titlebar
#define STR_TWBM_TITLE           "OpenTM2 Community Edition"

#define STR_TWBM_TITLE_LOGOS     "n/a"

